{% set name = "molsystem" %}
{% set version = "2021.9.11" %}
{% set sha256 = "663e1ac64075c01b132fdb63e815aa6904e2100069ede4c919539332aadc3dd2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - numpy
    - openbabel
    - pandas
    - pathvalidate
    - pycifrw
    - python >=3.7

test:
  imports:
    - molsystem
  commands:
    - pip check
  requires:
    - openbabel
    - pip

about:
  home: https://github.com/molssi-seamm/molsystem
  summary: A Python package for handling molecular and periodic systems.
  license: LGPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/molsystem/

extra:
  recipe-maintainers:
    - paulsaxe
